# Generated by Django 5.2.16 on 2026-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
